// ============================================================
// js/data.js — All Local Dummy Data for Bantul Creative Village
// ============================================================

const marketplaceProjects = [
  {
    id: 1,
    icon: "puzzle",
    title: "Desain Identitas Visual Kerajinan Kasongan",
    description: "Buat branding komprehensif untuk pengrajin gerabah Kasongan agar bisa bersaing di pasar internasional.",
    location: "Kasongan, Bantul",
    categories: ["Desain Grafis", "Branding"],
    status: "Open",
    deadline: "30 Jun 2026",
    prize: "Rp 3.500.000",
  },
  {
    id: 2,
    icon: "camera",
    title: "Dokumentasi Foto & Video Batik Imogiri",
    description: "Abadikan proses pembuatan batik tulis tradisional Imogiri dengan estetika modern untuk keperluan promosi.",
    location: "Imogiri, Bantul",
    categories: ["Fotografi", "Videografi"],
    status: "Open",
    deadline: "15 Jul 2026",
    prize: "Rp 2.800.000",
  },
  {
    id: 3,
    icon: "globe",
    title: "Website E-Commerce Produk Kulit Manding",
    description: "Kembangkan toko online yang elegan untuk kerajinan kulit berkualitas tinggi dari sentra Manding.",
    location: "Manding, Bantul",
    categories: ["Web Dev", "UI/UX"],
    status: "In Review",
    deadline: "20 Jul 2026",
    prize: "Rp 5.200.000",
  },
  {
    id: 4,
    icon: "megaphone",
    title: "Kampanye Media Sosial Wisata Parangtritis",
    description: "Kelola strategi konten dan kampanye digital untuk meningkatkan kunjungan wisatawan ke Parangtritis.",
    location: "Parangtritis, Bantul",
    categories: ["Digital Marketing", "Konten"],
    status: "Open",
    deadline: "5 Aug 2026",
    prize: "Rp 4.100.000",
  },
  {
    id: 5,
    icon: "palette",
    title: "Ilustrasi Mural untuk Kampung Wisata",
    description: "Ciptakan mural bertema budaya Bantul yang instagramable untuk mempercantik kampung wisata setempat.",
    location: "Dlingo, Bantul",
    categories: ["Ilustrasi", "Seni Publik"],
    status: "Open",
    deadline: "25 Jul 2026",
    prize: "Rp 6.000.000",
  },
  {
    id: 6,
    icon: "music",
    title: "Aransemen & Rekaman Musik Tradisional",
    description: "Produksi album musik gamelan Bantul yang diaransemen ulang dengan sentuhan kontemporer.",
    location: "Bantul Kota",
    categories: ["Musik", "Audio Produksi"],
    status: "Closed",
    deadline: "1 Jun 2026",
    prize: "Rp 7.500.000",
  },
];

const aiMatchProjects = [
  {
    id: 1,
    matchPercent: 92,
    title: "Desain Poster & Flyer Festival Budaya Bantul",
    location: "Bantul Kota",
    description: "Kami butuh desainer grafis kreatif untuk membuat materi visual festival budaya tahunan Bantul yang mampu menarik 10.000+ pengunjung.",
    skills: ["Adobe Illustrator", "Adobe Photoshop", "Typography"],
    applicants: 8,
    deadline: "28 Jun 2026",
    status: "Open",
  },
  {
    id: 2,
    matchPercent: 87,
    title: "Pengembangan Aplikasi Mobile Wisata Bantul",
    location: "Remote / Bantul",
    description: "Bantu kami membuat aplikasi wisata interaktif yang memandu turis menjelajahi spot-spot tersembunyi di Bantul dengan augmented reality.",
    skills: ["React Native", "UI/UX Design", "Figma"],
    applicants: 14,
    deadline: "10 Jul 2026",
    status: "Open",
  },
  {
    id: 3,
    matchPercent: 81,
    title: "Copywriting & Konten Produk UMKM Kasongan",
    location: "Kasongan, Bantul",
    description: "Tulis deskripsi produk yang menarik dan storytelling brand untuk 50+ produk kerajinan gerabah yang akan dipasarkan di platform nasional.",
    skills: ["Copywriting", "SEO Writing", "Bahasa Indonesia"],
    applicants: 5,
    deadline: "20 Jul 2026",
    status: "Open",
  },
  {
    id: 4,
    matchPercent: 78,
    title: "Motion Graphic & Video Profil Desa Wisata",
    location: "Dlingo, Bantul",
    description: "Produksi video profil desa wisata Dlingo dengan animasi motion graphic yang memukau untuk keperluan promosi ke investor dan wisatawan.",
    skills: ["After Effects", "Premiere Pro", "Motion Design"],
    applicants: 11,
    deadline: "5 Aug 2026",
    status: "Open",
  },
  {
    id: 5,
    matchPercent: 74,
    title: "Strategi & Kelola Iklan Digital UMKM Manding",
    location: "Manding, Bantul",
    description: "Kelola kampanye Google Ads dan Meta Ads untuk pengrajin kulit Manding dengan target ROAS minimal 4x dalam 3 bulan.",
    skills: ["Google Ads", "Meta Ads", "Data Analytics"],
    applicants: 3,
    deadline: "15 Aug 2026",
    status: "Open",
  },
  {
    id: 6,
    matchPercent: 69,
    title: "UI/UX Design Sistem Manajemen Pesanan Kerajinan",
    location: "Remote",
    description: "Rancang antarmuka sistem manajemen pesanan yang intuitif untuk membantu pengrajin Bantul mengelola order dari berbagai platform.",
    skills: ["Figma", "User Research", "Prototyping"],
    applicants: 7,
    deadline: "1 Sep 2026",
    status: "Open",
  },
];

const trailLocations = [
  {
    id: 1,
    icon: "pottery",
    name: "Kasongan Pottery Village",
    tag: "Kasongan",
    description: "Sentra kerajinan gerabah terbesar di Bantul. Temukan pengrajin berpengalaman yang membuat berbagai produk ekspor berkualitas tinggi.",
    projects: 3,
    rating: 4.9,
    categories: ["Kerajinan", "Gerabah", "Ekspor"],
    lat: "60%",
    lng: "40%",
  },
  {
    id: 2,
    icon: "waves",
    name: "Parangtritis Beach Creative Hub",
    tag: "Parangtritis",
    description: "Komunitas kreatif di tepi pantai selatan. Fotografi, videografi, dan content creation dengan backdrop alam yang luar biasa.",
    projects: 5,
    rating: 4.8,
    categories: ["Fotografi", "Konten", "Wisata"],
    lat: "80%",
    lng: "55%",
  },
  {
    id: 3,
    icon: "bag",
    name: "Manding Leather Craft Center",
    tag: "Manding",
    description: "Pusat kerajinan kulit premium Bantul. Pengrajin terampil menghasilkan tas, sepatu, dan aksesoris kulit berkualitas internasional.",
    projects: 4,
    rating: 4.7,
    categories: ["Kerajinan Kulit", "Fashion", "Ekspor"],
    lat: "45%",
    lng: "30%",
  },
  {
    id: 4,
    icon: "fabric",
    name: "Imogiri Batik Heritage",
    tag: "Imogiri",
    description: "Warisan batik tulis autentik dari lereng pegunungan. Setiap lembar kain adalah karya seni bernilai tinggi yang penuh makna budaya.",
    projects: 2,
    rating: 4.9,
    categories: ["Batik", "Tekstil", "Warisan Budaya"],
    lat: "30%",
    lng: "65%",
  },
  {
    id: 5,
    icon: "mountain",
    name: "Dlingo Nature Art Village",
    tag: "Dlingo",
    description: "Desa wisata alam di perbukitan dengan komunitas seniman mural dan instalasi seni. Destinasi ideal untuk proyek seni publik.",
    projects: 3,
    rating: 4.6,
    categories: ["Seni Publik", "Mural", "Alam"],
    lat: "25%",
    lng: "45%",
  },
  {
    id: 6,
    icon: "music-note",
    name: "Bantul Music & Culture Center",
    tag: "Bantul Kota",
    description: "Pusat seni pertunjukan dan produksi musik tradisional. Berkolaborasi dengan seniman gamelan dan penari tradisional berbakat.",
    projects: 6,
    rating: 4.8,
    categories: ["Musik", "Seni Pertunjukan", "Budaya"],
    lat: "50%",
    lng: "50%",
  },
];

const portfolioProjects = [
  {
    id: 1,
    icon: "chart",
    title: "Rebranding Visual Kerajinan Kasongan Export",
    description: "Transformasi identitas visual 12 UMKM gerabah Kasongan meningkatkan daya saing produk di pasar internasional.",
    impact: "+200% peningkatan engagement di media sosial dan 3 kontrak ekspor baru senilai Rp 150 juta.",
    metrics: [
      { icon: "trending-up", label: "+200% Engagement" },
      { icon: "package", label: "3 Kontrak Ekspor" },
      { icon: "dollar", label: "Rp 150 Juta Revenue" },
    ],
    date: "Maret 2026",
    rating: 5.0,
    freelancer: "Arya Kusuma",
    category: "Desain Grafis",
  },
  {
    id: 2,
    icon: "video",
    title: "Kampanye Video Wisata Parangtritis",
    description: "Produksi seri video dokumenter destinasi wisata Parangtritis yang viral di platform digital nasional.",
    impact: "+500% lonjakan kunjungan wisatawan dan peningkatan signifikan pendapatan pelaku UMKM sekitar pantai.",
    metrics: [
      { icon: "eye", label: "2.3 Juta Views" },
      { icon: "users", label: "+500% Kunjungan" },
      { icon: "trending-up", label: "+180% UMKM Revenue" },
    ],
    date: "Februari 2026",
    rating: 4.9,
    freelancer: "Sinta Dewi",
    category: "Videografi",
  },
  {
    id: 3,
    icon: "shopping-bag",
    title: "E-Commerce Platform Kerajinan Manding",
    description: "Pengembangan toko online terintegrasi untuk 20 pengrajin kulit Manding dengan sistem manajemen pesanan otomatis.",
    impact: "Omzet digital meningkat dari 0 ke Rp 80 juta/bulan dalam 60 hari pertama setelah peluncuran.",
    metrics: [
      { icon: "shopping-cart", label: "Rp 80 Juta/Bulan" },
      { icon: "users", label: "20 Pengrajin Aktif" },
      { icon: "star", label: "4.8 Rating Toko" },
    ],
    date: "Januari 2026",
    rating: 4.8,
    freelancer: "Budi Santoso",
    category: "Web Development",
  },
  {
    id: 4,
    icon: "map-pin",
    title: "Peta Interaktif Batik Heritage Trail Imogiri",
    description: "Aplikasi web peta interaktif yang memandu wisatawan menjelajahi sejarah dan keindahan batik tulis Imogiri.",
    impact: "Diunduh 5.000+ kali dalam 30 hari pertama dan menjadi referensi Dinas Pariwisata Bantul.",
    metrics: [
      { icon: "download", label: "5.000+ Unduhan" },
      { icon: "map", label: "15 Titik Heritage" },
      { icon: "award", label: "Ref. Dinas Pariwisata" },
    ],
    date: "Desember 2025",
    rating: 4.8,
    freelancer: "Rina Putri",
    category: "UI/UX & Dev",
  },
];
