// ============================================================
// js/data.js — All Local Dummy Data for Bantul Creative Village
// ============================================================

const marketplaceProjects = [
  {
    id: 1,
    icon: "palette",
    title: "Brand Identity Kedai Kopi Lokal",
    description: "Membangun identitas visual baru untuk kedai kopi lokal yang akan melakukan ekspansi ke beberapa kota di Indonesia. Proyek meliputi pembuatan logo, pemilihan warna, tipografi, dan brand guideline.",
    requirements: "1. Memiliki portofolio Branding.\n2. Menguasai Adobe Illustrator.\n3. Menyediakan maksimal 3 revisi.\n4. Menyerahkan file AI, SVG, PNG, dan PDF.",
    location: "Yogyakarta",
    categories: ["Branding", "Graphic Design"],
    status: "Open",
    deadline: "20 Jul 2026",
    prize: "Rp 4.500.000",
  },
  {
    id: 2,
    icon: "camera",
    title: "Dokumentasi Festival Kuliner Tradisional",
    description: "Mengabadikan seluruh rangkaian festival kuliner dalam bentuk foto profesional dan video highlight untuk kebutuhan promosi digital.",
    requirements: "1. Memiliki kamera sendiri.\n2. Menguasai editing dasar.\n3. Bersedia bekerja selama acara berlangsung.",
    location: "Bantul, DIY",
    categories: ["Photography", "Videography", "Kuliner"],
    status: "Open",
    deadline: "28 Jul 2026",
    prize: "Rp 3.200.000",
  },
  {
    id: 3,
    icon: "palette",
    title: "Redesign UI Aplikasi Pembelajaran",
    description: "Merancang ulang tampilan aplikasi pembelajaran agar lebih modern, sederhana, dan mudah digunakan oleh siswa maupun guru.",
    requirements: "1. Menguasai Figma.\n2. Membuat prototype interaktif.\n3. Menyusun design system.",
    location: "Sleman, DIY",
    categories: ["UI/UX Design", "Pendidikan"],
    status: "In Review",
    deadline: "5 Aug 2026",
    prize: "Rp 5.800.000",
  },
  {
    id: 4,
    icon: "globe",
    title: "Website Desa Wisata",
    description: "Membangun website responsif yang menampilkan informasi destinasi wisata, paket wisata, galeri, artikel, dan sistem reservasi online.",
    requirements: "1. Menguasai React atau Laravel.\n2. Responsive Design.\n3. Integrasi formulir reservasi.",
    location: "Gunungkidul, DIY",
    categories: ["Web Development", "Pariwisata"],
    status: "Open",
    deadline: "12 Aug 2026",
    prize: "Rp 7.000.000",
  },
  {
    id: 5,
    icon: "globe",
    title: "Aplikasi Mobile Bank Sampah",
    description: "Mengembangkan aplikasi Android untuk memudahkan masyarakat melakukan pencatatan dan penukaran sampah menjadi poin.",
    requirements: "1. Flutter atau React Native.\n2. Terhubung dengan Firebase.\n3. Source code diserahkan melalui GitHub.",
    location: "Yogyakarta",
    categories: ["Mobile Development", "Lingkungan"],
    status: "Open",
    deadline: "18 Aug 2026",
    prize: "Rp 8.500.000",
  },
  {
    id: 6,
    icon: "puzzle",
    title: "Campaign Media Sosial Produk Fashion Lokal",
    description: "Merancang strategi pemasaran digital untuk meningkatkan awareness dan penjualan produk fashion lokal melalui Instagram dan TikTok.",
    requirements: "1. Berpengalaman mengelola Social Media.\n2. Memahami Meta Ads.\n3. Membuat content plan selama 30 hari.",
    location: "Bandung",
    categories: ["Digital Marketing", "Social Media", "Fashion"],
    status: "Open",
    deadline: "30 Jul 2026",
    prize: "Rp 4.800.000",
  },
  {
    id: 7,
    icon: "puzzle",
    title: "Artikel SEO Teknologi AI",
    description: "Menulis artikel berkualitas mengenai perkembangan Artificial Intelligence yang dioptimalkan untuk mesin pencari.",
    requirements: "1. Minimal 1000 kata.\n2. Original tanpa plagiarisme.\n3. Memahami riset keyword.",
    location: "Remote",
    categories: ["Content Writing", "SEO", "Teknologi"],
    status: "Open",
    deadline: "8 Aug 2026",
    prize: "Rp 2.700.000",
  },
  {
    id: 8,
    icon: "palette",
    title: "Ilustrasi Buku Cerita Anak Nusantara",
    description: "Membuat ilustrasi penuh warna untuk buku cerita anak bertema budaya lokal Indonesia sebanyak 20 halaman.",
    requirements: "1. Menguasai digital illustration.\n2. Gaya ilustrasi ramah anak.\n3. Menyerahkan file PSD dan PNG.",
    location: "Solo",
    categories: ["Illustration", "Budaya Lokal", "Pendidikan"],
    status: "In Review",
    deadline: "15 Aug 2026",
    prize: "Rp 5.200.000",
  },
  {
    id: 9,
    icon: "camera",
    title: "Video Motion Graphic Kampanye Lingkungan",
    description: "Membuat motion graphic berdurasi satu menit untuk kampanye pengurangan sampah plastik dan pelestarian lingkungan.",
    requirements: "1. Menguasai Adobe After Effects.\n2. Resolusi Full HD.\n3. Menyerahkan file project.",
    location: "Semarang",
    categories: ["Motion Graphic", "Video Editing", "Lingkungan"],
    status: "Open",
    deadline: "22 Aug 2026",
    prize: "Rp 4.300.000",
  },
  {
    id: 10,
    icon: "music",
    title: "Festival Musik Tradisional Nusantara",
    description: "Membantu perencanaan, koordinasi, dan pelaksanaan festival musik tradisional yang melibatkan berbagai komunitas seni daerah.",
    requirements: "1. Berpengalaman sebagai Event Organizer.\n2. Mampu berkoordinasi dengan banyak pihak.\n3. Siap bekerja di lapangan.",
    location: "Yogyakarta",
    categories: ["Event Organizer", "Musik", "Seni Pertunjukan"],
    status: "Open",
    deadline: "28 Aug 2026",
    prize: "Rp 9.000.000",
  },
];

const aiMatchProjects = [
  {
    id: 1,
    matchPercent: 92,
    title: "Desain Poster & Flyer Festival Budaya Bantul",
    location: "Bantul Kota",
    description: "Kami membutuhkan desainer grafis kreatif dan inovatif untuk merancang materi visual komprehensif untuk Festival Budaya Bantul tahunan. Proyek ini mencakup desain poster utama, flyer digital untuk media sosial, banner cetak, dan materi promosi lainnya. Tujuannya adalah menciptakan identitas visual yang kuat yang menonjolkan kekayaan tradisi lokal dengan sentuhan modern yang memukau, mampu menarik lebih dari 10.000 pengunjung dari berbagai daerah. Anda akan bekerja sama erat dengan tim panitia untuk memastikan setiap desain mencerminkan tema 'Harmoni Bantul'.",
    requirements: "1. Wajib memiliki portofolio desain grafis yang kuat, terutama untuk event atau festival budaya.\n2. Bersedia melakukan revisi desain hingga 3 kali berdasarkan feedback panitia.\n3. Menyelesaikan seluruh materi promosi sesuai timeline yang disepakati (H-14 acara).\n4. Menyerahkan source file (AI/PSD) dan file siap cetak beresolusi tinggi.\n5. Pembayaran dilakukan dalam 2 tahap: 50% di muka dan 50% setelah seluruh deliverables diterima.",
    skills: ["Adobe Illustrator", "Adobe Photoshop", "Typography", "Visual Branding", "Layout Design", "Cultural Arts"],
    applicants: 8,
    deadline: "28 Jun 2026",
    status: "Open",
    prize: "Rp 3.000.000 - Rp 5.000.000",
  },
  {
    id: 2,
    matchPercent: 87,
    title: "Pengembangan Aplikasi Mobile Wisata Bantul",
    location: "Remote / Bantul",
    description: "Bantu kami membuat aplikasi wisata interaktif yang memandu turis menjelajahi spot-spot tersembunyi di Bantul dengan augmented reality.",
    skills: ["React Native", "UI/UX Design", "Figma"],
    applicants: 14,
    deadline: "10 Jul 2026",
    status: "Open",
  },
  {
    id: 3,
    matchPercent: 81,
    title: "Copywriting & Konten Produk UMKM Kasongan",
    location: "Kasongan, Bantul",
    description: "Tulis deskripsi produk yang menarik dan storytelling brand untuk 50+ produk kerajinan gerabah yang akan dipasarkan di platform nasional.",
    skills: ["Copywriting", "SEO Writing", "Bahasa Indonesia"],
    applicants: 5,
    deadline: "20 Jul 2026",
    status: "Open",
  },
  {
    id: 4,
    matchPercent: 78,
    title: "Motion Graphic & Video Profil Desa Wisata",
    location: "Dlingo, Bantul",
    description: "Produksi video profil desa wisata Dlingo dengan animasi motion graphic yang memukau untuk keperluan promosi ke investor dan wisatawan.",
    skills: ["After Effects", "Premiere Pro", "Motion Design"],
    applicants: 11,
    deadline: "5 Aug 2026",
    status: "Open",
  },
  {
    id: 5,
    matchPercent: 74,
    title: "Strategi & Kelola Iklan Digital UMKM Manding",
    location: "Manding, Bantul",
    description: "Kelola kampanye Google Ads dan Meta Ads untuk pengrajin kulit Manding dengan target ROAS minimal 4x dalam 3 bulan.",
    skills: ["Google Ads", "Meta Ads", "Data Analytics"],
    applicants: 3,
    deadline: "15 Aug 2026",
    status: "Open",
  },
  {
    id: 6,
    matchPercent: 69,
    title: "UI/UX Design Sistem Manajemen Pesanan Kerajinan",
    location: "Remote",
    description: "Rancang antarmuka sistem manajemen pesanan yang intuitif untuk membantu pengrajin Bantul mengelola order dari berbagai platform.",
    skills: ["Figma", "User Research", "Prototyping"],
    applicants: 7,
    deadline: "1 Sep 2026",
    status: "Open",
  },
];

const trailLocations = [
  {
    id: 1,
    icon: "pottery",
    name: "Kasongan Pottery Village",
    tag: "Kasongan",
    description: "Sentra kerajinan gerabah terbesar di Bantul. Temukan pengrajin berpengalaman yang membuat berbagai produk ekspor berkualitas tinggi.",
    projects: 3,
    rating: 4.9,
    categories: ["Kerajinan", "Gerabah", "Ekspor"],
    lat: "60%",
    lng: "40%",
  },
  {
    id: 2,
    icon: "waves",
    name: "Parangtritis Beach Creative Hub",
    tag: "Parangtritis",
    description: "Komunitas kreatif di tepi pantai selatan. Fotografi, videografi, dan content creation dengan backdrop alam yang luar biasa.",
    projects: 5,
    rating: 4.8,
    categories: ["Fotografi", "Konten", "Wisata"],
    lat: "80%",
    lng: "55%",
  },
  {
    id: 3,
    icon: "bag",
    name: "Manding Leather Craft Center",
    tag: "Manding",
    description: "Pusat kerajinan kulit premium Bantul. Pengrajin terampil menghasilkan tas, sepatu, dan aksesoris kulit berkualitas internasional.",
    projects: 4,
    rating: 4.7,
    categories: ["Kerajinan Kulit", "Fashion", "Ekspor"],
    lat: "45%",
    lng: "30%",
  },
  {
    id: 4,
    icon: "fabric",
    name: "Imogiri Batik Heritage",
    tag: "Imogiri",
    description: "Warisan batik tulis autentik dari lereng pegunungan. Setiap lembar kain adalah karya seni bernilai tinggi yang penuh makna budaya.",
    projects: 2,
    rating: 4.9,
    categories: ["Batik", "Tekstil", "Warisan Budaya"],
    lat: "30%",
    lng: "65%",
  },
  {
    id: 5,
    icon: "mountain",
    name: "Dlingo Nature Art Village",
    tag: "Dlingo",
    description: "Desa wisata alam di perbukitan dengan komunitas seniman mural dan instalasi seni. Destinasi ideal untuk proyek seni publik.",
    projects: 3,
    rating: 4.6,
    categories: ["Seni Publik", "Mural", "Alam"],
    lat: "25%",
    lng: "45%",
  },
  {
    id: 6,
    icon: "music-note",
    name: "Bantul Music & Culture Center",
    tag: "Bantul Kota",
    description: "Pusat seni pertunjukan dan produksi musik tradisional. Berkolaborasi dengan seniman gamelan dan penari tradisional berbakat.",
    projects: 6,
    rating: 4.8,
    categories: ["Musik", "Seni Pertunjukan", "Budaya"],
    lat: "50%",
    lng: "50%",
  },
];


const SKILL_OPTIONS = [
  "Branding", "Graphic Design", "Photography", "Videography", "Video Editing", 
  "UI/UX Design", "Web Development", "Mobile Development", "Digital Marketing", 
  "Content Writing", "Copywriting", "SEO", "Illustration", "Motion Graphic", "Social Media",
  "Pariwisata", "Kuliner", "Kriya", "Budaya Lokal", "Fashion", "Musik", "Pendidikan", 
  "Teknologi", "Lingkungan", "Event Organizer", "Seni Pertunjukan"
];


const portfolioData = [
  {
    id: 1,
    freelancerId: 1,
    title: "Rebranding Desa Wisata Kasongan",
    client: "Koperasi Pengrajin Kasongan",
    image: "https://images.unsplash.com/photo-1618220179428-22790b46a014?auto=format&fit=crop&q=80&w=800",
    date: "Ags 2025",
    tags: ["Branding", "Visual Identity"],
    description: "Pembuatan identitas visual baru yang menonjolkan nilai historis kerajinan gerabah, lengkap dengan panduan aplikasi pada kemasan dan media sosial.",
    impact: {
      type: "Peningkatan Penjualan",
      value: "+45%",
      label: "Dalam 3 bulan setelah implementasi"
    }
  },
  {
    id: 2,
    freelancerId: 2,
    title: "Video Promosi Kuliner Mangut Lele",
    client: "Paguyuban Kuliner Sewon",
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800",
    date: "Okt 2025",
    tags: ["Video Editing", "Content Creation"],
    description: "Produksi video dokumenter pendek berdurasi 3 menit yang menceritakan sejarah dan proses pembuatan mangut lele tradisional.",
    impact: {
      type: "Social Reach",
      value: "120K+",
      label: "Views di Instagram Reels"
    }
  },
  {
    id: 3,
    freelancerId: 1,
    title: "Website Interaktif Pengrajin Batik",
    client: "Batik Giriloyo",
    image: "https://images.unsplash.com/photo-1516062423079-7ca13cdc7f5a?auto=format&fit=crop&q=80&w=800",
    date: "Jan 2026",
    tags: ["Web Development", "UI/UX"],
    description: "Pengembangan website e-commerce dengan fitur tur virtual 360 derajat ke area workshop pembuatan batik.",
    impact: {
      type: "Pasar Baru",
      value: "Ekspor",
      label: "Ke 3 negara di Asia Tenggara"
    }
  }
];

const portfolioProjects = [
  {
    id: 1,
    icon: "chart",
    title: "Rebranding Visual Kerajinan Kasongan Export",
    description: "Transformasi identitas visual 12 UMKM gerabah Kasongan meningkatkan daya saing produk di pasar internasional.",
    impact: "+200% peningkatan engagement di media sosial dan 3 kontrak ekspor baru senilai Rp 150 juta.",
    metrics: [
      { icon: "trending-up", label: "+200% Engagement" },
      { icon: "package", label: "3 Kontrak Ekspor" },
      { icon: "dollar", label: "Rp 150 Juta Revenue" },
    ],
    date: "Maret 2026",
    rating: 5.0,
    freelancer: "Arya Kusuma",
    category: "Desain Grafis",
  },
  {
    id: 2,
    icon: "video",
    title: "Kampanye Video Wisata Parangtritis",
    description: "Produksi seri video dokumenter destinasi wisata Parangtritis yang viral di platform digital nasional.",
    impact: "+500% lonjakan kunjungan wisatawan dan peningkatan signifikan pendapatan pelaku UMKM sekitar pantai.",
    metrics: [
      { icon: "eye", label: "2.3 Juta Views" },
      { icon: "users", label: "+500% Kunjungan" },
      { icon: "trending-up", label: "+180% UMKM Revenue" },
    ],
    date: "Februari 2026",
    rating: 4.9,
    freelancer: "Sinta Dewi",
    category: "Videografi",
  },
  {
    id: 3,
    icon: "shopping-bag",
    title: "E-Commerce Platform Kerajinan Manding",
    description: "Pengembangan toko online terintegrasi untuk 20 pengrajin kulit Manding dengan sistem manajemen pesanan otomatis.",
    impact: "Omzet digital meningkat dari 0 ke Rp 80 juta/bulan dalam 60 hari pertama setelah peluncuran.",
    metrics: [
      { icon: "shopping-cart", label: "Rp 80 Juta/Bulan" },
      { icon: "users", label: "20 Pengrajin Aktif" },
      { icon: "star", label: "4.8 Rating Toko" },
    ],
    date: "Januari 2026",
    rating: 4.8,
    freelancer: "Budi Santoso",
    category: "Web Development",
  },
  {
    id: 4,
    icon: "map-pin",
    title: "Peta Interaktif Batik Heritage Trail Imogiri",
    description: "Aplikasi web peta interaktif yang memandu wisatawan menjelajahi sejarah dan keindahan batik tulis Imogiri.",
    impact: "Diunduh 5.000+ kali dalam 30 hari pertama dan menjadi referensi Dinas Pariwisata Bantul.",
    metrics: [
      { icon: "download", label: "5.000+ Unduhan" },
      { icon: "map", label: "15 Titik Heritage" },
      { icon: "award", label: "Ref. Dinas Pariwisata" },
    ],
    date: "Desember 2025",
    rating: 4.8,
    freelancer: "Rina Putri",
    category: "UI/UX & Dev",
  },
];

if (typeof window !== 'undefined') {
  window.portfolioData = portfolioData;
  window.projectsData = marketplaceProjects;
  window.aiMatchProjects = aiMatchProjects;
  // TODO: Restore when Trail Map dataset is reintroduced.
  //  window.trailMapVillages = trailMapVillages;
  window.portfolioProjects = portfolioProjects;
  window.SKILL_OPTIONS = SKILL_OPTIONS;
}
